---
title: "R Notebook"
output: html_notebook
---
## Converting Tabular data to row data
```{r}
#Load data
str(UCBAdmissions)
UCBAdmissions

```

```{r}
#The problem
admit.fail<-(UCBAdmissions$Admit) #won't work
plot(UCBAdmissions$Admit)#won't work

```

```{r}
plot(UCBAdmissions) # works but niot what we wanted

```

```{r}
# marginal frequency
margin.table(UCBAdmissions,1) #admit
margin.table(UCBAdmissions,2)#gender
margin.table(UCBAdmissions,3)#dept
margin.table(UCBAdmissions)#total
```

```{r}
admit.dept<-margin.table(UCBAdmissions,3) #dept
admit.dept
str(admit.dept)
barplot(admit.dept)
```

```{r}
prop.table(admit.dept)
round(prop.table(admit.dept),2)
```

```{r}
admit1 <- as.data.frame.table(UCBAdmissions)  # Coerces to data frame
admit2 <- lapply(admit1, function(x)rep(x, admit1$Freq))  # Repeats each row by Freq
admit3 <- as.data.frame(admit2)  # Converts from list back to data frame
admit4 <- admit3[, -4]  # Removes fifth column with frequencies
# Or do it all in one go
admit.rows <- as.data.frame(lapply(as.data.frame.table(UCBAdmissions), function(x)rep(x, as.data.frame.table(UCBAdmissions)$Freq)))[, -4]
str(admit.rows)
admit.rows[1:10, ]  # View first ten rows of data (of 4526)
```

