---
title: "R Notebook"
output: html_notebook
---
#Creating pie charts for categorical variables  

```{r}
require(datasets)
data("chickwts")

```

```{r}
feeds<-table(chickwts$feed)
feeds
```

```{r}
pie(feeds)
```

```{r}
pie(feeds[order(feeds,decreasing =TRUE)],
    init.angle = 90,
    clockwise  =TRUE,
    col=c("seashell","cadetblue2","lightpink","lightcyan","plum1","papayawhip"),
    main="Pie Chart of feeds from  chickwts")
```

```{r}
#problems in pie chart
#Can't differentiate between the size of the pie .
pie.a<-c(22,14,18,20,14,12)
pie.b<-c(20,18,16,18,16,22)
pie.c<-c(12,14,20,18,14,22)
colors<-c("grey","yellow","green","blue","white","lightskyblue")

#changing graphical parameter for a minute
oldpar<-par() # stores old graphical parameters
par(mfrow=c(1,3), # num . row/cols
cex.main=3) #main title 3 times bigger
pie(pie.a,main="Pie A",col=colors)
pie(pie.b,main="Pie B",col=colors)
pie(pie.c,main="Pie C",col=colors)



```



```{r}
#in barplot we can easily identify the 
barplot(pie.a,main="Pie A",col=colors)
barplot(pie.b,main="Pie B",col=colors)
barplot(pie.c,main="Pie C",col=colors)


```
```{r}
#Cleaning up

par(oldpar)
rm(list=ls())
```

